-- MySQL Script generated by MySQL Workbench
-- 11/23/16 21:50:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DreamDrinkDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DreamDrinkDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DreamDrinkDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `DreamDrinkDB` ;

-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `image_path` VARCHAR(45) NULL,
  `unit` INT NOT NULL,
  INDEX `unit_idx` (`unit` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `unit_fk`
    FOREIGN KEY (`unit`)
    REFERENCES `DreamDrinkDB`.`Unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`User` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `firstname` VARCHAR(30) NULL,
  `lastname` VARCHAR(45) NULL,
  `isAdmin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Drink` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `creator` VARCHAR(20) NULL,
  `public` TINYINT(1) NULL,
  `createdAt` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `creator_fk_idx` (`creator` ASC),
  CONSTRAINT `creator_fk`
    FOREIGN KEY (`creator`)
    REFERENCES `DreamDrinkDB`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Ingredients_for_Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Ingredients_for_Drink` (
  `ingredient_id` INT NOT NULL,
  `drink_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `ingredient_fk_idx` (`ingredient_id` ASC),
  INDEX `drink_fk_idx` (`drink_id` ASC),
  PRIMARY KEY (`ingredient_id`, `drink_id`),
  CONSTRAINT `ingredient_fk`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `DreamDrinkDB`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `drink_fk`
    FOREIGN KEY (`drink_id`)
    REFERENCES `DreamDrinkDB`.`Drink` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Rating` (
  `user_id` VARCHAR(20) NOT NULL,
  `drink_id` INT NOT NULL,
  `rating` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`, `drink_id`),
  INDEX `drink_fk_idx` (`drink_id` ASC),
  CONSTRAINT `user_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DreamDrinkDB`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `drink_fk1`
    FOREIGN KEY (`drink_id`)
    REFERENCES `DreamDrinkDB`.`Drink` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Image` (
  `id` INT NOT NULL,
  `path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DreamDrinkDB`.`Images_for_Drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DreamDrinkDB`.`Images_for_Drink` (
  `drink_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`drink_id`, `image_id`),
  INDEX `image_fk_idx` (`image_id` ASC),
  CONSTRAINT `drink_fk2`
    FOREIGN KEY (`drink_id`)
    REFERENCES `DreamDrinkDB`.`Drink` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `image_fk2`
    FOREIGN KEY (`image_id`)
    REFERENCES `DreamDrinkDB`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
