<div class="leftBar">
</div>
<div class="content">
    <h1>Über uns</h1>
    <p>Wir wollen die besten Drinks!</p>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
    fasdfasdfdsf<br/>
</div>

<div class="rightBar">
    <?php
        $drinkSearch = new DrinkSearch();
        $drinkSearch->render($this->lang);
    ?>
</div>